### ISSUE TITLE
Apresentação da Proposta da Solução (Slide)

### ISSUE THREAD

**Issue by ThiagoTerrinha** [ICEI-PUC-Minas-PMV-ADS/sistema-lar-sao-vicente-de-paulo#9]
Deve ser entregue na pasta [apresentacao](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e5-proj-empext-t2-sistema-lar-sao-vicente-de-paula/tree/4e94ae6fb076d54c454b72599924b189e322ffb6/apresentacao) no formato PDF.

Deve conter no slide:
- A descrição do cliente
- O Project Model Canvas
- Diagrama de Caso de Uso.

Sugestão: usar modelos prontos do Canva.

**Comment by marianoContin** [comment]
[Lar São Vicente de Paulo - slide.pdf](https://github.com/ICEI-PUC-Minas-PMV-ADS/sistema-lar-sao-vicente-de-paulo/files/14474679/Lar.Sao.Vicente.de.Paulo.-.slide.pdf)
